version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8084:8080"
    volumes:
      - jenkins_home:/var/jenkins_home  # Volume para persistir dados do Jenkins
      - /var/run/docker.sock:/var/run/docker.sock  # Monta o socket do Docker

volumes:
  jenkins_home:
