#!/usr/bin/env groovy
pipeline {
    agent any  // Define que o pipeline pode ser executado em qualquer agente
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'maven'
                }
            }
            steps {
                sh 'mvn package -Dmaven.test.skip=true'
            }
        }
    }
}